<?php
function enqueue_live_chat() { if(current_user_can('subscriber')) {
    return;
  } ?>

<div id="betterdocs-ia"></div>
<link rel="stylesheet" href="https://fjellestad.design/wp-content/plugins/betterdocs-pro/public/modules/instant-answer.css">
<style type="text/css">.betterdocs-widget-container{z-index:9999}.betterdocs-conversation-container, .betterdocs-footer-wrapper, .betterdocs-launcher, .betterdocs-ask-wrapper .betterdocs-ask-submit{background-color:#2f5d62}.betterdocs-footer-wrapper .bd-ia-feedback-wrap, .betterdocs-footer-wrapper .bd-ia-feedback-response{background-color:#2f5d62}.betterdocs-header-wrapper .betterdocs-header .inner-container.betterdocs-active-answer .toggle:first-of-type > p, .betterdocs-header-wrapper .betterdocs-header .inner-container.betterdocs-active-ask .toggle:last-of-type > p{color:#2f5d62}.betterdocs-header-wrapper .betterdocs-header .inner-container.betterdocs-active-answer .toggle:first-of-type svg, .betterdocs-header-wrapper .betterdocs-header .inner-container.betterdocs-active-ask .toggle:last-of-type svg{fill:#2f5d62}.betterdocs-header-wrapper .betterdocs-header .inner-container, .betterdocs-footer-wrapper .betterdocs-footer-emo > div{background-color:#5e8b7e}.betterdocs-launcher[type=button], .betterdocs-launcher[type=button]:focus {background-color:#2f5d62}.betterdocs-widget-container .betterdocs-launcher[type=button]:hover {background-color:#5e8b7e !important}.betterdocs-tab-content-wrapper .bdc-search-box .search-button svg {fill:#2f5d62}.betterdocs-footer-wrapper .bd-ia-feedback-response .feedback-success-icon {fill: #2f5d62}.betterdocs-tab-ask .betterdocs-ask-wrapper .betterdocs-ask-submit { background-color: #2f5d62}.betterdocs-tab-ask .betterdocs-ask-wrapper .betterdocs-ask-submit:hover { background-color: #5e8b7e}.betterdocs-messages-container .betterdocs-modal-wrapper .betterdocs-modal-content-container .betterdocs-ia-content h1 { font-size: 26px}.betterdocs-messages-container .betterdocs-modal-wrapper .betterdocs-modal-content-container .betterdocs-ia-content h2 { font-size: 24px}.betterdocs-messages-container .betterdocs-modal-wrapper .betterdocs-modal-content-container .betterdocs-ia-content h3 { font-size: 22px}.betterdocs-messages-container .betterdocs-modal-wrapper .betterdocs-modal-content-container .betterdocs-ia-content h4 { font-size: 20px}.betterdocs-messages-container .betterdocs-modal-wrapper .betterdocs-modal-content-container .betterdocs-ia-content h5 { font-size: 18px}.betterdocs-messages-container .betterdocs-modal-wrapper .betterdocs-modal-content-container .betterdocs-ia-content h6 { font-size: 16px}.betterdocs-messages-container .betterdocs-modal-wrapper .betterdocs-modal-content-container .betterdocs-ia-content,
            .betterdocs-messages-container .betterdocs-modal-wrapper .betterdocs-modal-content-container .betterdocs-ia-content p,
            .betterdocs-messages-container .betterdocs-modal-wrapper .betterdocs-modal-content-container .betterdocs-ia-content strong { font-size: 16px}</style>
<script>window.betterdocs = {"CHAT":{"label":"Sp\u00f8r","subtitle":"Sliter du med noe? Send oss en melding.","subtitle_two":"Generelt svarer vi innen 12-24 timer."},"ANSWER":{"label":"Svar","subtitle":"Fjellestad Design's brukerst\u00f8tte"},"URL":"https:\/\/fjellestad.design\/wp-json\/wp\/v2\/docs","SEARCH":{"SEARCH_URL":"https:\/\/fjellestad.design\/wp-json\/wp\/v2\/docs","SEARCH_PLACEHOLDER":"S\u00f8k etter l\u00f8sninger...","OOPS":"Oops...","NOT_FOUND":"Vi fant ingen artikler som samsvarer med s\u00f8ket ditt. Pr\u00f8v \u00e5 s\u00f8ke etter et nytt begrep."},"FEEDBACK":{"DISPLAY":false,"SUCCESS":"Takk for tilbakemeldingen","TEXT":"How did you feel?","URL":"https:\/\/fjellestad.design\/?rest_route=\/betterdocs\/feedback"},"RESPONSE":{"title":"Takk for din melding!"},"ASKFORM":{"NAME":"Navn","EMAIL":"Epostadresse","SUBJECT":"Emne","TEXTAREA":"Hvordan kan vi hjelpe?","ATTACHMENT":"St\u00f8tter bare .jpg, .png, .jpeg, .gif-filer","SENDING":"Sender","SEND":"Send"},"ASK_URL":"https:\/\/fjellestad.design\/?rest_route=\/betterdocs\/ask","BRANDING":{"show":false},"THANKS":{"title":"Takk","text":"Vi har mottatt din melding!"}};</script>
<script src="https://fjellestad.design/wp-content/plugins/betterdocs-pro/public/modules/instant-answer.js"></script>
<?php    }

add_action( 'admin_footer', 'enqueue_live_chat' ); 